# Generated by Django 4.1.7 on 2023-04-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licence', '0003_student_teacher_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
    ]
