# Generated by Django 4.1.7 on 2023-04-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licence', '0004_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=20)),
                ('period_i', models.CharField(max_length=50)),
                ('period_ii', models.CharField(max_length=50)),
                ('period_iii', models.CharField(max_length=50)),
                ('lunch', models.CharField(max_length=50)),
                ('period_iv', models.CharField(max_length=50)),
                ('period_v', models.CharField(max_length=50)),
                ('period_vi', models.CharField(max_length=50)),
                ('period_vii', models.CharField(max_length=50)),
            ],
        ),
    ]
