# Generated by Django 4.1.7 on 2023-04-14 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='password',
            new_name='password1',
        ),
    ]
