# Generated by Django 4.1.7 on 2023-04-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextra',
            name='email',
            field=models.CharField(default=40, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3')], default='one', max_length=10),
        ),
    ]
