# Generated by Django 4.1.7 on 2023-04-29 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_teacherextra_email_alter_studentextra_cl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherextra',
            name='email',
        ),
    ]
