# Generated by Django 4.1.7 on 2023-05-03 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_adminextra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentextra',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='studentextra',
            name='roll',
        ),
        migrations.AddField(
            model_name='studentextra',
            name='lv',
            field=models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3')], default='L1', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.group'),
        ),
    ]
