# Generated by Django 4.1.7 on 2023-05-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_studentextra_fee_remove_studentextra_roll_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='roll',
        ),
    ]
