# Generated by Django 4.1.7 on 2023-05-06 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_attendance_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='cl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.group'),
        ),
    ]
