# Generated by Django 4.1.7 on 2023-05-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_attendance_cl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherextra',
            name='salary',
        ),
    ]
