# Generated by Django 4.1.7 on 2023-05-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_group_id_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='cl',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
