# Generated by Django 4.1.7 on 2023-05-07 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_teacherextra_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextra',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.group'),
        ),
    ]
