# Generated by Django 4.1.7 on 2023-05-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_teacherextra_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherextra',
            name='group',
        ),
        migrations.AddField(
            model_name='teacherextra',
            name='groups',
            field=models.ManyToManyField(blank=True, to='home.group'),
        ),
    ]
