# Generated by Django 4.1.7 on 2023-05-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_days_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duration',
            old_name='Time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='duration',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
