# Generated by Django 4.1.7 on 2023-05-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_time_duration_end_time_duration_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='level',
            field=models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3')], default='L1', max_length=10),
        ),
    ]
