# Generated by Django 4.1.7 on 2023-05-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
