# Generated by Django 4.1.7 on 2023-05-12 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.room')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.duration')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.module')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teacherextra')),
            ],
        ),
    ]
