# Generated by Django 4.1.7 on 2023-05-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_rename_grouplevel_activities_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='name',
            new_name='module',
        ),
    ]
