# Generated by Django 4.1.7 on 2023-05-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_attendance_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.activities')),
            ],
        ),
    ]
