# Generated by Django 4.1.7 on 2023-05-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_registeredactivities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisteredActivities',
        ),
    ]
