# Generated by Django 4.2.1 on 2023-05-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_delete_registeredactivities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherextra',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='teacherextra_set', to='home.group'),
        ),
    ]
