# Generated by Django 4.2.1 on 2023-05-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_teacherextra_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='position_in_week',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='days',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
