# Generated by Django 4.2.1 on 2023-05-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_days_position_in_week_alter_days_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='days',
            name='position_in_week',
        ),
    ]
