# Generated by Django 4.2.1 on 2023-05-21 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_days_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'ordering': ['duration']},
        ),
        migrations.AlterModelOptions(
            name='days',
            options={'ordering': ['order']},
        ),
    ]
